Specific disbursal for singular mode
t0xic0der/syngrafias pull request #109
Opened 2021-01-22 04:47 UTC by t0xic0der

**Description**
This PR fixes https://github.com/t0xic0der/syngrafias/issues/108.

**Have you read the [Contributing Guidelines](https://github.com/t0xic0der/syngrafias/blob/master/CONTRIBUTING.md) before opening this PR**
Yes.

**Notes for Reviewers**
This addition somehow breaks the event logging display for the Unity Mode. Don't get me wrong - events do get logged actively but they can be seen only once when you click on the "View activities" option. On subsequent invoking of that option, no activities would show up even when logging is active. You can check the logging using developer tools.

I am not quite able to figure out as to why this is happening. The event logging in the cellular mode has an identical syntax and usage, and works just fine but the one at the unity mode does not. I could use some assistance in tracking down the fault behind this. Tagging for reference. @VaibhavSaini19 @s-katte @shivangswain.

2021-01-22 04:47 UTC, t0xic0der commented
Please review carefully and diagnose the listed issue. Thanks.

2021-01-22 11:12 UTC, VaibhavSaini19 requested changes

2021-01-22 11:12 UTC, VaibhavSaini19 commented on templates/singular.html
> +        </div>
The reason behind the mentioned bug is that you have 2 divs with id `actijuxt`. The first time the user tries to track the activity, the data is logged in the correct modal, but in subsequent tracking, it gets logged to the other div (which I believe is for the `Help and support` modal). Changing the id of the other div fixes the bug.

2021-01-22 14:02 UTC, t0xic0der commented on templates/singular.html
> +        </div>
Ohhh got it! Thanks @VaibhavSaini19 - you're a lifesaver. :fire:

2021-01-23 04:45 UTC, t0xic0der commented
The most recent commit https://github.com/t0xic0der/syngrafias/pull/109/commits/7d39f9881a458f79a73e2e56315e1db387105196 should fix the display and handle malformed JSON documents' exception.

2021-01-23 05:20 UTC, VaibhavSaini19 approved these changes
LGTM

2021-01-23 05:23 UTC, t0xic0der commented
Thanks for the review. :smile:

2021-01-23 05:23 UTC, merged

2021-01-23 08:51 UTC, shivangswain reviewed
Now works good on my end too.