Make textarea and output full screen
t0xic0der/syngrafias pull request #51
Opened 2020-11-10 02:24 UTC by s-katte

## solves #50 
### Here is the screenshot of changes made.
![image](https://user-images.githubusercontent.com/39235382/98619703-cd4dee80-2329-11eb-881b-f5b0fb882be0.png)

2020-11-10 03:10 UTC, t0xic0der requested changes
Try to ensure that only the entirety of the available view space is claimed and not more. With resolutions like 1440p or 2160p (2560x1440 and 3840x2160 respectively), your code might end up occupying less than the complete view space.

2020-11-10 03:10 UTC, t0xic0der commented on templates/asciidoc.html
> +                                <textarea style="height: 81vh;" rows="2" id="textdata" class="monotext" onkeyup="autoconv(); dispatch();"></textarea>
81vh is unfortunately not uniform for all the resolutions.

This is how it looks like in 768p.
![image](https://user-images.githubusercontent.com/49605954/98622440-8662f780-232f-11eb-8cd2-8f54840de8b1.png)

This is how it looks like in 720p.
![image](https://user-images.githubusercontent.com/49605954/98622478-a4305c80-232f-11eb-99ca-2b399a3a2b0f.png)

This is how it looks like in 900p.
![image](https://user-images.githubusercontent.com/49605954/98622527-c2965800-232f-11eb-997f-9fed2279fffc.png)

And finally this is how it looks like in 1080p.
![image](https://user-images.githubusercontent.com/49605954/98622581-df329000-232f-11eb-804d-8320e14b4f02.png)

As you can see, 1920x1080 is the only resolution where it looks the way it is supposed to and hence leaves away the general scrollbar. For the remaining resolutions, eg. 1600x900, 1280x720 and 1366x768 which are in fact standard resolutions for devices - it tries to occupy more space than what is available on the viewport - thus enabling the scrollbar.

2020-11-10 03:10 UTC, t0xic0der commented on templates/asciidoc.html
> +                            <div class="ui form textbase" style="overflow-y: scroll; height:81vh; border: 1px solid #dedede; border-radius: 5px; padding: 1%;" id="otptdata"></div>
Has the same repercussions as mentioned in the former review comment.

2020-11-10 03:30 UTC, s-katte commented on templates/asciidoc.html
> +                            <div class="ui form textbase" style="overflow-y: scroll; height:81vh; border: 1px solid #dedede; border-radius: 5px; padding: 1%;" id="otptdata"></div>
Sure, will do it.

2020-11-11 01:38 UTC, s-katte commented
Have a look at it now @t0xic0der

2020-12-06 12:30 UTC, closed without merging