[WIP] Tabs UI
t0xic0der/syngrafias pull request #87
Opened 2020-12-26 07:14 UTC by shivangswain

## Description

Adds the tabbed UI

**Have you read the [Contributing Guidelines](https://github.com/t0xic0der/syngrafias/blob/master/CONTRIBUTING.md) before opening this PR**
Yes

## Screenshot
![image](https://user-images.githubusercontent.com/33395916/103147078-610f3900-4777-11eb-9a59-cba65d8390c8.png)

---

## Things to do

- [X] Add tab UI
- [X] Make tabs scrollable
- [ ] Add X to close on each tab
- [ ] Make editor full height

2020-12-27 04:52 UTC, t0xic0der commented
@shivangswain At the end of the PR, remove the sticky nature of the menubar as the page would no longer be scrollable. The sticky property would not be needed anymore and it also messes up #88.

2020-12-28 04:26 UTC, t0xic0der commented
@shivangswain Check the following image out.

![image](https://user-images.githubusercontent.com/49605954/103189507-f08d2700-48f2-11eb-9f62-91997c888e1b.png)

You need to add the copy button too at the menu bar.

2020-12-31 03:09 UTC, t0xic0der requested changes
When clicked on the REMOVE CELL icon (The 'X' icon I mean) - The following error shows up. Please look into it.

![image](https://user-images.githubusercontent.com/49605954/103392387-a3ec5a80-4b43-11eb-980a-9b697d2a99b0.png)

2020-12-31 03:10 UTC, t0xic0der commented
@VaibhavSaini19 @s-katte Please go ahead and review this plocs.

2020-12-31 03:20 UTC, t0xic0der commented
Here's the preview.

![image](https://user-images.githubusercontent.com/49605954/103392721-4822d100-4b45-11eb-8579-2a13f1ee8633.png)

2020-12-31 03:44 UTC, VaibhavSaini19 commented on static/jscn/syngrafias.js
> +    );
Could you format this with correct indentation please

2020-12-31 03:51 UTC, VaibhavSaini19 commented on static/jscn/syngrafias.js
>          minSize: [150, 150],
The minimum size for the Split functionality isn't working on my end

2020-12-31 03:54 UTC, VaibhavSaini19 requested changes
Bugs mentioned in the comments above

2020-12-31 04:58 UTC, t0xic0der commented on static/jscn/syngrafias.js
> +    );
> Also, it would be great if you could format this code with proper indentation as well

+1 to this

2020-12-31 05:08 UTC, s-katte requested changes
Few changes requested:

- [ ] Put a cross on the top-right corner of Usage Tips to remove it if not required.
- [ ] In tabs UI, if we open multiple tabs, and have a content in one tab with overflow-y (_just the point when scroll bar comes up_), the height of tabs section changes, improve this.

filled with content
![image](https://user-images.githubusercontent.com/39235382/103394917-71e1f500-4b51-11eb-976f-471f80f1939e.png)  

without content
![image](https://user-images.githubusercontent.com/39235382/103394936-8e7e2d00-4b51-11eb-87df-45a692819445.png)

- [ ] same is the issue if we toggle the split view --> when only preview is open, height reduces by some pixels.
- [ ] remove extra padding in the name of tabs to use the extra space for the content writing
- [ ] Add horizontal padding for the tabs, it does not align with rest ui
- [ ] Here is another major bug
![image](https://user-images.githubusercontent.com/39235382/103395140-9be7e700-4b52-11eb-86d3-ae56d8353772.png)
- [ ] After the file is opened followed by parse, on clicking continue, the modal persists and content is not loaded properly, do test that once again.
- [ ] The cell is there, but still unable to delete it
![image](https://user-images.githubusercontent.com/39235382/103395246-4cee8180-4b53-11eb-81ea-be46587e575a.png)
- [ ] After deleting a tab, the focus must be on the last tab, instead of none.
- [ ] In tabs UI, on clicking ```i```, for information, the title should be ```Tab Information```, instead of ```Cell Information```

2020-12-31 06:07 UTC, t0xic0der commented
The documents do not open up.

![image](https://user-images.githubusercontent.com/49605954/103396870-9216b180-4b5b-11eb-8d5e-9122c8b87f4e.png)

There is no option to switch over to the singular mode.

Clicking on the `i` icon gets me more console errors.

![image](https://user-images.githubusercontent.com/49605954/103396924-e28e0f00-4b5b-11eb-824e-ec06f13b8273.png)

Condense the tab padding and font sizes.

![image](https://user-images.githubusercontent.com/49605954/103397075-998a8a80-4b5c-11eb-8a2f-d1e487694ba9.png)

2023-01-16 08:53 UTC, closed without merging